name: Release Docker image

on:
  workflow_call:
    inputs:
      volto-version:
        required: true
        type: string
      base-image-name:
        required: true
        type: string
      suffix:
        required: true
        type: string
      registry:
        required: true
        type: string
      platforms:
        required: true
        type: string
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.base-image-name }}-${{ inputs.suffix }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}.{{patch}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: ${{ inputs.platforms }}
          context: .
          file: Dockerfile.${{ inputs.suffix }}
          build-args: |
            VOLTO_VERSION=${{ inputs.volto-version }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
