name: Build images

on:
  push:
  workflow_dispatch:

env:
  BASE_IMAGE_NAME: ghcr.io/ericof/frontend
  PLATFORMS: linux/amd64

permissions:
  packages: write

jobs:

  volto-version:
    runs-on: ubuntu-latest
    outputs:
      BASE_TAG: ${{ steps.vars.outputs.VOLTO_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compute VOLTO_VERSION value to be used with all images
        id: vars
        run: echo "VOLTO_VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

  release-builder:
    uses: ./.github/workflows/docker-release.yml
    with:
      volto-version: ${{ needs.volto-version.outputs.VOLTO_VERSION }}
      base-image-name: ${{ env.BASE_IMAGE_NAME }}
      suffix: builder
      registry: ghcr.io
      platforms: ${{ env.PLATFORMS }}
    secrets:
      regsitry-username: ${{ github.actor }}
      regsitry-password: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - volto-version

  release-prod:
    uses: ./.github/workflows/docker-release.yml
    with:
      volto-version: ${{ needs.volto-version.outputs.VOLTO_VERSION }}
      base-image-name: ${{ env.BASE_IMAGE_NAME }}
      suffix: prod
      registry: ghcr.io
      platforms: ${{ env.PLATFORMS }}
    secrets:
      regsitry-username: ${{ github.actor }}
      regsitry-password: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - volto-version

  release-dev:
    uses: ./.github/workflows/docker-release.yml
    with:
      volto-version: ${{ needs.volto-version.outputs.VOLTO_VERSION }}
      base-image-name: ${{ env.BASE_IMAGE_NAME }}
      suffix: dev
      registry: ghcr.io
      platforms: ${{ env.PLATFORMS }}
    secrets:
      regsitry-username: ${{ github.actor }}
      regsitry-password: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - volto-version
      - release-builder
