name: Build images

on:
  push:
  workflow_dispatch:

env:
  BASE_IMAGE_NAME: ghcr.io/ericof/frontend
  PLATFORMS: linux/amd64

permissions:
  packages: write

jobs:

  volto-version:
    runs-on: ubuntu-latest
    outputs:
      BASE_IMAGE_NAME: ${{ steps.vars.outputs.BASE_IMAGE_NAME }}
      PLATFORMS: ${{ steps.vars.outputs.PLATFORMS }}
      VOLTO_VERSION: ${{ steps.vars.outputs.VOLTO_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set BASE_IMAGE_NAME, PLATFORMS, VOLTO_VERSION
        id: vars
        run: |
          echo "BASE_IMAGE_NAME=$BASE_IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "PLATFORMS=$PLATFORMS" >> $GITHUB_OUTPUT
          echo "VOLTO_VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

  release-builder:
    needs:
      - volto-version
    uses: ./.github/workflows/docker-release.yml
    with:
      volto-version: ${{ needs.volto-version.outputs.VOLTO_VERSION }}
      base-image-name: ${{ needs.volto-version.outputs.BASE_IMAGE_NAME }}
      suffix: builder
      registry: ghcr.io
      platforms: ${{ needs.volto-version.outputs.PLATFORMS  }}
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  release-prod:
    uses: ./.github/workflows/docker-release.yml
    with:
      volto-version: ${{ needs.volto-version.outputs.VOLTO_VERSION }}
      base-image-name: ${{ needs.volto-version.outputs.BASE_IMAGE_NAME }}
      suffix: prod
      registry: ghcr.io
      platforms: ${{ needs.volto-version.outputs.PLATFORMS  }}
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - volto-version

  release-dev:
    uses: ./.github/workflows/docker-release.yml
    with:
      volto-version: ${{ needs.volto-version.outputs.VOLTO_VERSION }}
      base-image-name: ${{ needs.volto-version.outputs.BASE_IMAGE_NAME }}
      suffix: dev
      registry: ghcr.io
      platforms: ${{ needs.volto-version.outputs.PLATFORMS  }}
    secrets:
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
    needs:
      - volto-version
      - release-builder
